<?php
error_reporting(E_ERROR);
include('paged_database.php');
include('paged_errorhandlers.php');
include('paged_form_tokens.php');
include('paged_recommendations.php');
include('paged_sessions.php');
include('paged_tile.php');
include('paged_validate.php');
include('paged_user_notify.php');
?>